[versions]
kotlin = "1.9.22"
ktlint = "1.1.1"

[libraries]
assertK = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.0" }
css = { module = "com.helger:ph-css", version = "7.0.1" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.16.0" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
